name = "Field_Induced_Hall_Effect"
uuid = "f57a1fe4-d949-4368-b10e-a4b5a13ce036"
authors = ["Fernando Penaranda <fernandopenaranda@github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
